---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
