---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- type: file
  name: thumbnail
  label: thumbnail
  hidden: false
pages:
- content/post/test.md
- content/post/components-within-components.md
- content/post/great-article-on-duck-typing-in-javascript.md
- content/post/spring.schemas-and-spring.handlers-when-creating-uber-jar.md
