---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: thumbnail
  label: Thumbnail
  type: text
  hidden: false
  default: ''
pages:
- post/great-article-on-duck-typing-in-javascript.md
- post/spring.schemas-and-spring.handlers-when-creating-uber-jar.md
